### ISSUE TITLE
git hooks to update .py files in storage

### ISSUE THREAD

**Issue by roblesch** [Smarker/pybatchai#11]
Use hooks to update new versions of scripts and tests in storage

**Comment by Smarker** [comment]
@chrobles After looking into this, the most straightforward way is to upload the python scripts directory during travis deployment rather than git hooks.

[See my example here](https://github.com/Smarker/travis-deploy-sample). We can add a reference to this sample in `pybatchai`'s README. (if we have extra time, we could add sample deployment scripts for Azure Files, Gluster, etc. - for now I just did Azure Blob)
